### ISSUE TITLE
Missing License info

### ISSUE THREAD

**Issue by K1ll3rF0x** [stathissideris/www.clojurestacks.com#1]
This project does not specify a license yet. 
Could you add a license to make contributing possible?

**Comment by stathissideris** [comment]
Added https://creativecommons.org/licenses/by-sa/4.0/

**Comment by K1ll3rF0x** [comment]
@stathissideris Could you also add a different license for the software part of this blog?
Creative Commons BY-SA is a good pick for blog posts, but not so suitable for code: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software 
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available.

I suggests the following: 
1. Specify that the content of `_posts`-directory is under CC BY-SA 4.0 license.
2. All other content, such as code, styles etc. are under MIT-license. (You don't have to license logos or other images, if you don't want to open source them. But please specify it in the license conditions, if you are planning to exclude them.)

I'm planning to make a PR to make writing posts easier, if that is okay.
