### ISSUE TITLE
Refining the license notice

### ISSUE THREAD

**Issue by K1ll3rF0x** [stathissideris/www.clojurestacks.com#2]
Continuing from: #1 

Could you also add a different license for the software part of this blog?
Creative Commons BY-SA is a good pick for blog posts, but not so suitable for code: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software 
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available.

I suggests the following: 
1. Specify that the content of `_posts`-directory is under the CC BY-SA 4.0 license.
2. All other content, such as code, styles etc. could be under MIT-license. (You don't have to license logos or other images you have made, if you don't want to open source them. But please specify it in the license conditions if you are planning to exclude them.)

This enables improvement of the blog itself by the community.

**Comment by stathissideris** [comment]
More detailed terms added, I hope that's clear enough now!
